### ISSUE TITLE
Info: My additions to twan.sh

### ISSUE THREAD

**Issue by rc2dev** [linuxcaffe/tw-ann-hook#2]
Hi David,

Thanks for this useful script! I have been using it for some days, and ended up adding some features that are convenient to me, plus refactored it. So I thought it would be nice to share my modifications with you.

The changes:
- Don't add a new line at the beginning if the annotation is single-line.
- Allow to annotate from the CLI (just as in `task ID annotate foobar`).
- Improve regex ID/UUID checking.
- Refactor and move to Bash (I usually prefer to write in Bash over POSIX unless necessary).

My workflow is that I have a bunch of taskwarrior aliases such as `tad` for `task add`, `tm` for `task modify`, etc. To annotate, I write `tan`, which calls the script. I can either `tan ID This is an annotation.` or `tan ID` to write the annotation in the editor. 

[You can find the code here.](https://github.com/rc2dev/dotfiles/blob/master/.local/bin/tan)

**Comment by linuxcaffe** [comment]
Wow, yeah! That looks great! Much better than that crusty little script I had there :)  Thanks!
I'd be happy to merge a p/r or paste from your dotfiles, either way, I look forward to testing it!

**Comment by rc2dev** [comment]
Great! I'm opening a PR so you can review it.
