### ISSUE TITLE
on_modify_annotation_edit hook

### ISSUE THREAD

**Issue by linuxcaffe** [linuxcaffe/tw-ann-hook#5]
The command `task ID ann', without annotation text, will throw an error. This hook will instead open the editor for the annotation.

**Comment by linuxcaffe** [comment]
This hook might obviate the twan.sh script, but in a good way :)

**Comment by linuxcaffe** [comment]
@rccavalcanti it seems that you might use this sort of thing, and you're clearly a better programmer than I. How would you like to have a go at these hooks??

**Comment by rc2dev** [comment]
Hi David, 

I might try to implement that in the near future. I'll let you know.

**Comment by rc2dev** [comment]
Bad news: it looks like running `task ID annotate` will fail _without_ running the hooks. Same if you run something like `task ID mod` without the expected arguments.

I'm not very familiar with Taskwarrior hooks, but it seems that such a hook isn't possible.

**Comment by linuxcaffe** [comment]
ohh POO! Hmmm.. maybe taskwarrior needs an on-error_something.sh hook!

**Comment by linuxcaffe** [comment]
In the mean time, twan.sh will do the trick! Thanks for exploring the idea.
